# Vars
export EDITOR="vim"
export ARCHFLAGS="-arch x86_64"

# Colors
LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
export LS_COLORS
alias ls="ls -alh --color"

# Other Colors
alias grep="grep --color=auto"
export CLICOLOR=1

# Git prompt
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\w\[\033[32m\]\$(parse_git_branch)\[\033[00m\]$ "

# Add things to path
PATH=$PATH:~/tools/bin
